// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kimfcqjzyehxxpxmjqdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbWZjcWp6eWVoeHhweG1qcWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDE0NzksImV4cCI6MjA2MTE3NzQ3OX0.y0jw-xLdePurKGUDvErz2xCxTJbWuwXO2n21KOpNHgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);